const API_URL = 'ws://127.0.0.1:4000';

export const API_TYPES = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_ACTIVE: 'USER_ACTIVE',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_EXTERNAL_LOGIN: 'USER_EXTERNAL_LOGIN',
  USER_EXTERNAL_LOGOUT: 'USER_EXTERNAL_LOGOUT',
  ERROR: 'ERROR',
  MSG_FROM_USER: 'MSG_FROM_USER',
  MSG_SEND: 'MSG_SEND',
  MSG_DELIVER: 'MSG_DELIVER',
} as const;

export const CHECK_INTERVAL = 5000;

export default API_URL;
