export const TAG_NAMES = {
  div: 'div',
  button: 'button',
  form: 'form',
  input: 'input',
  textarea: 'textarea',
  label: 'label',
  span: 'span',
  p: 'p',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h5',
  h6: 'h6',
  ul: 'ul',
  li: 'li',
  a: 'a',
  img: 'img',
  svg: 'svg',
} as const;

export const EVENT_NAMES = {
  hashchange: 'hashchange',
  click: 'click',
  submit: 'submit',
  dragOver: 'dragover',
  dragDrop: 'drop',
  dragStart: 'dragstart',
  dragEnd: 'dragend',
  dragLeave: 'dragleave',
  dragEnter: 'dragenter',
  input: 'input',
  ended: 'ended',
} as const;
