export const TAG_NAMES = {
  MAIN: 'main',
  HEADER: 'header',
  FOOTER: 'footer',
  NAV: 'nav',
  SECTION: 'section',
  ARTICLE: 'article',
  ASIDE: 'aside',
  BUTTON: 'button',
  FORM: 'form',
  INPUT: 'input',
  LABEL: 'label',
  SELECT: 'select',
  TEXTAREA: 'textarea',
  SPAN: 'span',
  DIV: 'div',
  SVG: 'svg',
  A: 'a',
  I: 'i',
  P: 'p',
  UL: 'ul',
  OL: 'ol',
  LI: 'li',
  H1: 'h1',
  H2: 'h2',
  H3: 'h3',
  H4: 'h4',
  H5: 'h5',
  H6: 'h6',
  IMG: 'img',
  VIDEO: 'video',
  AUDIO: 'audio',
  SOURCE: 'source',
  TRACK: 'track',
  CANVAS: 'canvas',
  MAP: 'map',
  MARK: 'mark',
  DETAILS: 'details',
  SUMMARY: 'summary',
  PRE: 'pre',
  BLOCKQUOTE: 'blockquote',
  ADDRESS: 'address',
  DIVIDER: 'hr',
  TABLE: 'table',
  THEAD: 'thead',
  TBODY: 'tbody',
  TFOOT: 'tfoot',
  TR: 'tr',
  TD: 'td',
  TH: 'th',
} as const;

export const EVENT_NAMES = {
  CLICK: 'click',
  CHANGE: 'change',
  INPUT: 'input',
  SUBMIT: 'submit',
  KEYUP: 'keyup',
  KEYDOWN: 'keydown',
  SCROLL: 'scroll',
  RESIZE: 'resize',
  FOCUS: 'focus',
  BLUR: 'blur',
  CONTEXTMENU: 'contextmenu',
  DOM_CONTENT_LOADED: 'DOMContentLoaded',
  LOAD: 'load',
  ERROR: 'error',
  ANIMATIONSTART: 'animationstart',
  ANIMATIONEND: 'animationend',
  ANIMATIONITERATION: 'animationiteration',
  TRANSITIONEND: 'transitionend',
  POPSTATE: 'popstate',
  HASHCHANGE: 'hashchange',
  BEFOREUNLOAD: 'beforeunload',
  OPEN: 'open',
  CLOSE: 'close',
  MESSAGE: 'message',
} as const;

export const IS_DISABLED = {
  DISABLED: true,
  ENABLED: false,
} as const;
