const TAG_NAMES = {
  MAIN: 'main',
  HEADER: 'header',
  FOOTER: 'footer',
  NAV: 'nav',
  SECTION: 'section',
  ARTICLE: 'article',
  ASIDE: 'aside',
  BUTTON: 'button',
  FORM: 'form',
  INPUT: 'input',
  LABEL: 'label',
  SELECT: 'select',
  TEXTAREA: 'textarea',
  SPAN: 'span',
  DIV: 'div',
  I: 'i',
  P: 'p',
  UL: 'ul',
  OL: 'ol',
  LI: 'li',
  H1: 'h1',
  H2: 'h2',
  H3: 'h3',
  H4: 'h4',
  H5: 'h5',
  H6: 'h6',
  IMG: 'img',
  VIDEO: 'video',
  AUDIO: 'audio',
  SOURCE: 'source',
  TRACK: 'track',
  CANVAS: 'canvas',
  MAP: 'map',
  MARK: 'mark',
  DETAILS: 'details',
  SUMMARY: 'summary',
  PRE: 'pre',
  BLOCKQUOTE: 'blockquote',
  ADDRESS: 'address',
  DIVIDER: 'hr',
} as const;

export default TAG_NAMES;
